export const PRODUCT_SECTIONS = {
  loans: {
    key: 'loans',
    title: 'Микрозаймы',
    categorySlug: 'loans',
    categorySlugs: ['loans'],
    listPath: '/admin/products/loans',
    paths: ['/loans'],
    formVariant: 'loan',
  },
  'consumer-loans': {
    key: 'consumer-loans',
    title: 'Потреб. кредиты',
    categorySlug: 'consumer-loans',
    categorySlugs: ['consumer-loans', 'collateral-loans'],
    listPath: '/admin/products/consumer-loans',
    paths: ['/consumer-loans', '/collateral-loans'],
    formVariant: 'loan',
  },
  'debit-cards': {
    key: 'debit-cards',
    title: 'Дебетовые карты',
    categorySlug: 'debit-cards',
    categorySlugs: ['debit-cards'],
    listPath: '/admin/products/debit-cards',
    paths: ['/cards'],
    formVariant: 'card',
  },
  'credit-cards': {
    key: 'credit-cards',
    title: 'Кредитные карты',
    categorySlug: 'credit-cards',
    categorySlugs: ['credit-cards'],
    listPath: '/admin/products/credit-cards',
    paths: ['/auto-loans'],
    formVariant: 'card',
  },
  'settlement-accounts': {
    key: 'settlement-accounts',
    title: 'Расчётные счета',
    categorySlug: 'settlement-accounts',
    categorySlugs: ['settlement-accounts'],
    listPath: '/admin/products/settlement-accounts',
    paths: ['/settlement-accounts'],
    formVariant: 'simple',
  },
  services: {
    key: 'services',
    title: 'Сервисы',
    categorySlug: 'services',
    categorySlugs: ['services'],
    listPath: '/admin/products/services',
    paths: ['/services'],
    formVariant: 'simple',
  },
  shops: {
    key: 'shops',
    title: 'Магазины',
    categorySlug: 'shops',
    categorySlugs: ['shops'],
    listPath: '/admin/products/shops',
    paths: ['/shops'],
    formVariant: 'simple',
  },
  obuchenie: {
    key: 'obuchenie',
    title: 'Обучение',
    categorySlug: 'obuchenie',
    categorySlugs: ['obuchenie', 'education'],
    listPath: '/admin/products/obuchenie',
    paths: ['/obuchenie', '/Education'],
    formVariant: 'simple',
  },
  jobs: {
    key: 'jobs',
    title: 'Вакансии',
    categorySlug: 'jobs',
    categorySlugs: ['jobs'],
    listPath: '/admin/products/jobs',
    paths: ['/Job'],
    formVariant: 'simple',
  },
};
